# Generated by Django 4.2.30 on 2026-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_companyhistory_companyinfo_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='photo',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='photo_url',
            field=models.URLField(blank=True, help_text='External image URL', max_length=500, null=True),
        ),
    ]
